source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GIGalleryPicker_Example', :exclusive => true do
  pod "GIGalleryPicker", :path => "../"
end

target 'GIGalleryPicker_Tests', :exclusive => true do
  pod "GIGalleryPicker", :path => "../"

  
end
